# Generated by Django 5.1 on 2024-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='Selected_precision',
            field=models.FloatField(default=0),
        ),
    ]
