# Generated by Django 5.1 on 2024-09-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_metricentry_t_alter_metricentry_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricentry',
            name='T',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metricentry',
            name='V',
            field=models.FloatField(default=0.0),
        ),
    ]
